### ISSUE TITLE
Equivalent of password_needs_rehash()

### ISSUE THREAD

**Issue by stpnkcrk** [spaze/encryption#2]
Hi Michal

I'm starting to use this library on my projects (initially to store OTP secrets in the database).

When considering key rotation, I think equivalent of `password_needs_rehash()` function would be useful. I'm using that currently to check whether bcrypt hash needs rehashing on user's login and was thinking about the same for this.

Yes, one could either re-encrypt it every time (every login) or run a foreach on all records on re-key, but that's not the point.

I believe the implementation is trivial and I'm more than happy to prepare PR.

Before I do that, I wanted to ask you whether you would consider this functionality to be merged or not?

Also, I was thinking about the best method name, `needsReencrypt(string $data): bool` maybe?

**Comment by spaze** [comment]
Hi @stpnkcrk! Yeah, I think that a good idea and something that's indeed missing so I'd definitely consider adding something like that.

Maybe `needsReEncrypt` with uppercase E would be a more correct name ("needs re-encrypt"), what do you think?

**Comment by stpnkcrk** [comment]
Fully agree. Just've found out that for example [AWS](https://docs.aws.amazon.com/kms/latest/APIReference/API_ReEncrypt.html) using `ReEncrypt` with capital E so that's another supporting argument.

`needsReEncrypt(string $data): bool` it is.

Thank you, I'll prepare the PR then.
